### ISSUE TITLE
Migrate asynctest to stdlib's AsyncMock

### ISSUE THREAD

**Issue by fabaff** [emlove/pyzerproc#3]
https://github.com/emlove/pyzerproc/blob/06a8994c8f59f29acb956d39ac8250f30cb13a80/requirements_dev.txt#L16

Asynctest doesn't work with Python 3.8 and above.

Asynctest upstream is aware of this breakage and recommends using the built-in AsyncMock instead.

See also Martiusweb/asynctest#144 and Martiusweb/asynctest#126

**Comment by emlove** [comment]
I've published version 0.4.8 that incorporates these dependency cleanups. Thanks for letting me know!

**Comment by fabaff** [comment]
Thanks a lot for the quick "intervention".
