### ISSUE TITLE
Tests recently started failing in nixpkgs

### ISSUE THREAD

**Issue by rmcgibbo** [emlove/pyzerproc#5]
* pyzerproc version: 0.4.8
* Python version: python3.8
* Operating System: linux

### Description

pyzeproc is packaged in nixpkgs for NixOS and Darwin, and it looks like the tests recently started failing: https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.python38Packages.pyzerproc.x86_64-linux.

Clearly the root cause must be nixpkgs bumping the version of one of the dependencies, but I don't have a lot of insight into what the failure might be from the log. I realize this may not directly be your fault at all, but if you have any insight, it would be appreciated.

**Comment by emlove** [comment]
Yeah, I can get this fixed next week. I've got requirements defined that are pretty permissive for using future package versions, so it's expected from time to time. Thanks for letting me know!

**Comment by emlove** [comment]
Should be fixed! I've pushed up version 0.4.9 with those changes.
